
@api = http://localhost:3000/products

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "name":"post desde vsc",
    "description":"no entendiendo nada igual todo bien",
    "quantity": 25555
}