
@api = http://localhost:3000/products

GET {{api}}

###
POST {{api}}
Content-Type: application/json

{
    "name":"sarasa desde vsc",
    "description":"llora",
    "quantity": 123456
}

###
GET {{api}}/5



### Borrando un prodcuto por ID
DELETE {{api}}/4


### contador

GET {{api}}/count


### update
PUT {{api}}/5 
Content-Type: application/json

{
    "name":"modificado ",
    "description":"desde put",
    "quantity": 2525
}